
name: Publish to NuGet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Pack the project
      run: dotnet pack --configuration Release --output ./artifacts


    - name: Publish Mizon.API.Client to NuGet
      run: dotnet nuget push ./artifacts/Mizon.API.Client.*.nupkg --api-key ${{ secrets.MIZON_API_CLIENT_NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json

    - name: Delete Mizon.API.Client.nupkg files
      run: rm -f ./artifacts/Mizon.API.Client.*.nupkg
      
    - name: Publish Mizon.API to NuGet
      run: dotnet nuget push ./artifacts/Mizon.API.*.nupkg --api-key ${{ secrets.MIZON_API_NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
